name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ github.repository_owner }}/docker-example:${{ steps.set_version.outputs.version }}-${{ steps.set_version.outputs.date }} .
    
    - name: Set version and date
      id: set_version
      run: |
        version=$(grep -o '<version>.*</version>' pom.xml | sed 's/<[^>]*>//g')
        date=$(date +'%Y%m%d%H%M%S')
        echo "::set-output name=version::${version}"
        echo "::set-output name=date::${date}"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker image
      run: docker push ${{ github.repository_owner }}/docker-example:${{ steps.set_version.outputs.version }}-${{ steps.set_version.outputs.date }}
