name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository_owner }}/docker-example:${{ steps.set_version.outputs.version }}-${{ github.run_number }}

      - name: Set version
        id: set_version
        run: echo ::set-output name=version::$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
